[package]
name = "convex_hulls"
version = "0.1.0"
authors = ["Hendrik Schawe <hendrik.schawe@uni-oldenburg.de>"]

[dependencies]
itertools = "*"
assert_approx_eq = "*"
rand = "*"

[features]
default = []
visual = []
